title: Alphonse
description: A self-hosted WhatsApp bot written in Go.
remote_theme: just-the-docs/just-the-docs
url: https://ortsax.github.io/Alphonse
baseurl: /Alphonse
color_scheme: dark

aux_links:
  "GitHub":
    - "https://github.com/ortsax/Alphonse"

footer_content: 'Released under the <a href="https://github.com/ortsax/Alphonse/blob/master/LICENSE">MIT License</a>.'

nav_sort: case_insensitive

plugins:
  - jekyll-remote-theme
